defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

wandb:
  entity: <entity>
  project: <project>

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

augmentations:
- rrc:
    enabled: false
    crop_min_scale: 0.08
    crop_max_scale: 1.0
  horizontal_flip:
    prob: 0.5
  vertical_flip:
    prob: 0.5
  crop_size: 120
  num_crops: 1


backbone:
  name: "vit_base"
  kwargs:
    patch_size: 15
    img_size: 120
    in_chans: 12
    multi_sensor_encoder_depth: 10
    cross_sensor_encoder_depth: 2
    masking_strategy: 'random'          # 'identical' | 'disjoint' | 'random'
    global_pool: 'avg'                  # 'avg' | 'token'

method_kwargs:
  decoder_embed_dim: 512
  decoder_depth: 8
  decoder_num_heads: 16
  decoding_strategy: 'specific'         # 'common' | 'specific'
  reconstruction_strategy: 'disjoint'   # 'identical' | 'disjoint'
  mask_ratio: 0.5
  norm_pix_loss: False                  # normalize pixel values in MSE loss
  apply_umr_loss: True
  apply_cmr_loss: True
  apply_mde_loss: False
  apply_mim_loss: True
  mim_temp: 0.5

data:
  dataset: "ben"
  root_dir: <path/to/lmdb/file>
  split_dir: <path/to/[train,test,val].csv>
  num_workers: 10
  num_bands: 12
  img_size: 120
  num_classes: 19

optimizer:
  batch_size: 128
  lr: 1.0e-4
  classifier_lr: 1.0e-4
  weight_decay: 0.05
  kwargs:
    betas: [0.9, 0.95]

scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0.0
  lr_decay_steps:
  min_lr: 0
  warmup_epochs: 10
  interval: step

checkpoint:
  dir: "trained_models"

find_unused_parameters: False
seed: 42

max_epochs: 150
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
precision: 16

